* Modify the shock-peakon solution of gDP 
  <2018-01-10 Wed>
** Simulate the shock-peakon solution of gDP successfully!!!
   <2018-01-10 Wed 02:40>
   It is result my mistake of taking wrong exact solution cause of the wrong understanding to g''(x). 
   It should be taken to 1 instead of 0 on the peakon points in the whole domain [0,1).
** TODO Search for the smooth exact solution for gDP to compute the accuracy list.
   SCHEDULED: <2018-01-10 Wed 03:00>
** Read the article [On the Cauchy problem for a weakly dissipative muDP equation]
*** TODO Figure out the blow up phenomena for gDP equation.
** discution with Xu.
** Profile time
   <2018-01-10 Wed 15:00>
*** one-shock-solu: "298s" (In lab 1214)
    polynomial: 1
    Meshsize: 160 
    RK_order: 3 
    CFL: 0.1
*** one-shock-solu: "533s" (In lab 1214)
    polynomial: 2
    Meshsize: 160 
    shocks: 1
    RK_order: 3 
    CFL: 0.1
*** three-shock-solu: "230s" (In lab 1214)
    Order_of_polynomial: 1 
    Meshsize: 160 
    shocks: 3
    RK_order: 3 
    CFL: 0.1
*** simulate the exact solution: "2666s" (In domi 216)
	Initial condition: 0.03*sin(2*pi*x)+0.5
    Order_of_polynomial: 3
    Meshsize: 640 
    RK_order: 3 
    CFL: 0.1 